name: dart_fast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Dongle
      fonts: 
        - asset: assets/fonts/Dongle-Regular.ttf
        - asset: assets/fonts/Dongle-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dongle-Light.ttf
          weight: 300
    - family: JetbrainsMono
      fonts: 
        - asset: assets/fonts/JetBrainsMono.ttf
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png

flutter_native_splash:
 color: "#89B0BD"
 image: assets/splash/splash.png
 android_12:
   image: assets/splash/splash_android.png
   color: "#89B0BD"
   icon_background_color: "#89B0BD"